/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/
module

import Strata.Transform.LoopElim
import Strata.Transform.InsertLoopInvariantAsserts
import Strata.Transform.NondetElim
import Strata.Transform.CallElim
import Strata.Languages.Core.ObligationExtraction
public import Strata.Languages.C_Simp.C_Simp
public import Strata.Languages.Core.SMTEncoder
import Std.Tactic.BVDecide.Normalize.Prop
import Strata.DL.Lambda.Denote.LExprAnnotated
public import Strata.DL.SMT.Denote
import Strata.Languages.C_Simp.DDMTransform.Translate
import Strata.Languages.C_Simp.Verify
import Strata.Languages.Core
import Strata.Languages.Core.DDMTransform.Translate
import Strata.Languages.Core.ProgramEval
public import Strata.DL.SMT.DatatypeEncoding
public import Strata.DL.SMT.RealAbstraction

-- For some reason shake wants to meta import the following
-- while lake itself only requires imports.

public meta import Strata.DL.SMT.Translate
import Strata.DL.SMT.Translate -- shake: keep
meta import Lean.Meta.Eval
import Lean.Meta.Tactic.Rewrite -- shake: keep
meta import Lean.Meta.Tactic.Rewrite
import Lean.Meta.Tactic.Unfold -- shake: keep
meta import Lean.Meta.Tactic.Unfold
import Lean.Meta.Eval -- shake: keep

open Lean hiding Options

public section

namespace Strata.SMT

structure SanitizedContext where
  sorts : Array Strata.DL.SMT.Sort := #[]
  ufs : Array UF := #[]
  ifs : Array IF := #[]
  axms : Array Term := #[]
  tySubst : Map String TermType := []
deriving Repr, Inhabited, DecidableEq

def SanitizedContext.ofCore (ctx : Core.SMT.Context) : SanitizedContext :=
  { sorts := ctx.sorts.toArray, ufs := ctx.ufs.toArray, ifs := ctx.ifs.toArray,
    axms := ctx.axms.toArray, tySubst := ctx.tySubst }

def SanitizedContext.toCore (ctx : SanitizedContext) : Core.SMT.Context :=
  -- Build each OrderedKeyedSet with `ofArrayUnchecked`, not `ofArray`.
  -- The reflection tactic `gen_smt_vcs` evaluates this context in the
  -- *kernel* and `ofArray` which uses `HashSet` insert-fold does not reduce.
  -- The fields come from `ofCore` which are already-deduped,
  -- so their keys are distinct and the invariant holds.
  { sorts := .ofArrayUnchecked ctx.sorts
    ufs := .ofArrayUnchecked ctx.ufs
    ifs := .ofArrayUnchecked ctx.ifs
    axms := .ofArrayUnchecked ctx.axms
    tySubst := ctx.tySubst
    datatypes := .empty
    seenDatatypes := {}
    datatypeFuns := {} }

abbrev SMTVC := String × SanitizedContext × List Term × Term
abbrev SMTVCs := List SMTVC

end Strata.SMT

namespace Core

abbrev CoreVC := Env × Imperative.ProofObligation Expression
abbrev coreVCs := List (Env × Imperative.ProofObligation Expression)

def genVCs (program : Program) (options : VerifyOptions := .default) : Option coreVCs := do
  let transform : Transform.CoreTransformM (Bool × Program) := do
    -- callElim first: without it a `call` contributes nothing, because the
    -- callee's postcondition is never assumed at the call site. Any property of
    -- a procedure that calls another -- every recursive one included -- is then
    -- unprovable, since the results of its own calls stay unconstrained. The
    -- solver-backed pipeline in `Verifier.transformPipelinePhases` has always
    -- run this phase; the metaverifier was simply missing it.
    let (_, programC) ← CallElim.callElim' program
    let (_, program') ← insertLoopInvariantAsserts programC
    let (_, program'') ← loopElim program'
    -- nondetElim must run before symbolic evaluation, which rejects surviving
    -- nondeterministic guards.
    nondetElim program''
  let (res, _) := StateT.run (ExceptT.run transform) Transform.CoreTransformState.emp
  let (_, program) ← res.toOption
  match Core.typeCheck options program with
  | .error _ => none
  | .ok tcProgram =>
    match Core.toCoreProofObligationProgram options tcProgram with
    | .error _ => none
    | .ok (oblProgram, _stats) =>
      match Core.ObligationExtraction.extractObligations oblProgram with
      | .error _ => none
      | .ok obligations =>
        let E := match Core.buildEnv options tcProgram Core.Factory with
          | .ok (initE, _) =>
            match Program.eval initE with
            | .ok (pEs, _) => pEs.head?.getD initE
            | .error _ => initE
          | .error _ => Env.init (empty_factory := true)
        return obligations.toList.map (fun ob => (E, ob))

end Core

namespace C_Simp

def genVCs (program : Strata.C_Simp.Program) (options : Core.VerifyOptions := .default) : Option Core.coreVCs := do
  let program := Strata.to_core program
  Core.genVCs program options

end C_Simp

namespace Strata

open StrataDDM

namespace MetaVerifier

/--
Options that affect the verification conditions generated by the metaverifier.

This is intentionally a small subset of `Core.VerifyOptions`: most of its
fields configure the solver, output, or pipeline stopping points, which have
no bearing on the generated VCs or their denotation.
-/
structure Options where
  /-- Use SMT-LIB Array theory for `Map` types instead of an uninterpreted
  sort with axiomatized `select`/`update` functions. -/
  useArrayTheory : Bool := true
  /-- Keep only the verification conditions carrying these labels.

  `smtVCsCorrect` otherwise means "every obligation in the whole program holds",
  which is the wrong question when one named contract is under study: the
  obligations of unrelated procedures, and the auto-generated safety checks of
  this one, all become the caller's problem. Naming a label narrows the
  statement to that contract.

  `none` keeps everything, so the default is unchanged. A label that matches
  nothing yields no obligations and `smtVCsCorrect` holds vacuously -- check the
  label against `genSMTVCs` output if a proof looks suspiciously easy. -/
  onlyLabels : Option (List String) := none

/--
Interpret metaverifier options as options for the Core verification pipeline.
-/
def Options.toVerifyOptions (options : Options) : Core.VerifyOptions :=
  { Core.VerifyOptions.default with
    verbose := .quiet
    useArrayTheory := options.useArrayTheory }

end MetaVerifier

/--
Generate verification conditions for a `StrataDDM.Program` by translating it to the
appropriate frontend verifier and collecting its deferred proof obligations.

Note that this can be extended to new dialects by using
`unsafe/@[implemented_by]` as in [`StrataBoole.MetaVerifier`](https://github.com/strata-org/Strata-Boole).
-/
def genCoreVCs (program : Program)
    (options : MetaVerifier.Options := {}) : Option Core.coreVCs := do
  if program.dialect == "Core" then
    let (program, #[]) := TransM.run default (translateProgram program) | none
    Core.genVCs program options.toVerifyOptions
  else if program.dialect == "C_Simp" then
    let (program, #[]) := C_Simp.TransM.run default (C_Simp.translateProgram program.commands) | none
    C_Simp.genVCs program options.toVerifyOptions
  else
    none

/--
Remove solver-side caches that destabilize definitional equality in metaprograms,
after replacing the datatype theory with its axiomatization.

Dropping `datatypes`/`seenDatatypes`/`datatypeFuns` used to be harmless only
because `denoteQuery` refused such contexts outright. It now costs something, so
`SMT.DatatypeEncoding.encode` first turns each datatype into an uninterpreted
sort, uninterpreted constructor/tester/selector functions, and axioms relating
them. The encoding declares signatures only and asserts nothing: an earlier
version also emitted the datatype laws as axioms, and on the Laurel prelude that
set turned out to be contradictory.

Every term the context carries is rewritten with that same encoding: the
program's own axioms and the bodies of its defined functions mention
constructors and selectors just as the goal does, and one missed occurrence
leaves an `Op.datatype_op` head with no denotation. The caller must rewrite the
goal and assumptions to match.
-/
private def sanitizeSMTContext (ctx : Core.SMT.Context)
    (enc : SMT.DatatypeEncoding.Encoding) : SMT.SanitizedContext :=
  let base := SMT.SanitizedContext.ofCore ctx
  let rewrite := SMT.DatatypeEncoding.rewriteTerm enc
  { base with
    -- Placed so that, once the context is reversed into binder order, the
    -- datatype sorts lead and the datatype functions trail -- which is the
    -- split `denoteQuerySupplying` interprets rather than quantifies. The two
    -- go opposite ways for the reasons given there. Order is otherwise
    -- immaterial: it only permutes the outer binders.
    sorts := base.sorts ++ enc.sorts
    ufs := enc.ufs ++ base.ufs
    ifs := base.ifs.map fun f => { f with body := rewrite f.body }
    axms := base.axms.map rewrite }

def Core.ProofObligation.toSMTObligation (E : Core.Env) (ob : Imperative.ProofObligation Core.Expression)
  (options : MetaVerifier.Options := {}) :
  Option SMT.SMTVC := do
    -- Seed the encoding context with the env's datatypes and the array-theory flag.
    let smtCtx := { Core.SMT.Context.default with
      datatypes := .ofFactory E.datatypes, useArrayTheory := options.useArrayTheory }
    -- Encode this single obligation from a fresh encoder state.
    let encState : Core.SMTEncodeState := .init { ctx := smtCtx }
    let maybeTerms := Core.encodeObligationToSMT E.factory encState ob
    match maybeTerms with
    | .error _ => none
    | .ok ({ assumptions := ts, varDefs, goal := t, ctx, .. }, _) =>
      -- For denotational semantics, variable definitions are equivalent to equalities
      let defAssumptions := varDefs.map fun d =>
        Strata.SMT.Factory.eq (.app (.uf ⟨d.name, [], d.ty⟩) [] d.ty) d.body
      let enc := SMT.DatatypeEncoding.encode ctx
      let rewrite := SMT.DatatypeEncoding.rewriteTerm enc
      let sanitized := sanitizeSMTContext ctx enc
      -- Reals last: it has to see the datatype axioms too, since a constructor
      -- can carry a real and its axioms would then mention one.
      let (terms, ufs, reals) :=
        SMT.RealAbstraction.abstractAll
          (#[rewrite t] ++ ((defAssumptions ++ ts).map rewrite).toArray ++ sanitized.axms)
          sanitized.ufs
      let goal := terms[0]!
      let assumptions := terms.extract 1 (terms.size - sanitized.axms.size)
      let axms := terms.extract (terms.size - sanitized.axms.size) terms.size
      let ifs := sanitized.ifs.map fun f =>
        { f with
          args := f.args.map fun v =>
            { v with ty := SMT.RealAbstraction.abstractTy v.ty }
          out := SMT.RealAbstraction.abstractTy f.out
          body := SMT.RealAbstraction.abstractTerm f.body }
      (ob.label,
       { sanitized with
         sorts := sanitized.sorts ++ reals.sorts
         ufs := ufs ++ reals.ufs
         ifs := ifs
         axms := axms },
       assumptions.toList, goal)

/--
Interpret a list of SMT verification conditions as the conjunction of their
denotations.
-/
noncomputable def denoteQueries (vcs : SMT.SMTVCs) : Option Prop := do
  match vcs with
  | [] => return True
  | (_, ctx, ts, t) :: vcs =>
    let p ← denoteQuery ctx.toCore ts t
    go vcs p
where
  go vcs p : Option Prop := do
  match vcs with
  | [] => return p
  | (_, ctx, ts, t) :: vcs =>
    let q ← denoteQuery ctx.toCore ts t
    go vcs (p ∧ q)

def toSMTVCs (vcs : Core.coreVCs)
    (options : MetaVerifier.Options := {}) : Option SMT.SMTVCs := do
  match vcs with
  | [] => return []
  | (E, ob) :: vcs =>
    let (label, ctx, ts, t) ← Core.ProofObligation.toSMTObligation E ob options
    let vcs ← toSMTVCs vcs options
    return (label, ctx, ts, t) :: vcs

/--
Generate SMT verification conditions for a `StrataDDM.Program`.
-/
def genSMTVCs (program : Program)
    (options : MetaVerifier.Options := {}) : Option SMT.SMTVCs := do
  let coreVCs ← genCoreVCs program options
  let vcs ← toSMTVCs coreVCs options
  match options.onlyLabels with
  | none => return vcs
  | some labels => return vcs.filter (fun (label, _, _, _) => labels.contains label)

/--
State semantic correctness of the SMT verification conditions generated for a
program under the given metaverifier options. For example,
`options.useArrayTheory` selects how the SMT encoder treats `Map` types: under
`true` they become SMT-LIB arrays, under `false` an uninterpreted sort with
axiomatized `select`/`update` functions.
-/
def smtVCsCorrect (program : Program)
    (options : MetaVerifier.Options := {}) : Prop :=
  match genSMTVCs program options with
  | some vcs => (denoteQueries vcs).getD False
  | none     => False

/--
Interpret a list of verification conditions under a fixed interpretation of the
datatype symbols, as the conjunction of their denotations.
-/
noncomputable def denoteQueriesIn (I : SuppliedInterp) (vcs : SMT.SMTVCs) : Option Prop := do
  match vcs with
  | [] => return True
  | (_, ctx, ts, t) :: vcs =>
    let p ← denoteQueryIn I ctx.toCore ts t
    go vcs p
where
  go vcs p : Option Prop := do
  match vcs with
  | [] => return p
  | (_, ctx, ts, t) :: vcs =>
    let q ← denoteQueryIn I ctx.toCore ts t
    go vcs (p ∧ q)

/--
State semantic correctness of a program's verification conditions *under one
interpretation* of its datatypes, rather than under all of them.

This is deliberately weaker than `smtVCsCorrect`, and the two must not be
conflated: a proof of this establishes the property in the intended model only.
That is the right question for finding bugs -- a property that fails on the
concrete datatype is a real defect, one that fails only in some exotic model is
not -- and it is the only question that can be asked at all here, since
`smtVCsCorrect` leaves every datatype sort abstract and so cannot decide a tag
test on a symbolic value.

`I` must interpret exactly the leading sorts and trailing functions of each
generated context; otherwise every query denotes to `none` and this is `False`.
-/
def smtVCsCorrectIn (program : Program) (I : SuppliedInterp)
    (options : MetaVerifier.Options := {}) : Prop :=
  match genSMTVCs program options with
  | some vcs => (denoteQueriesIn I vcs).getD False
  | none     => False

theorem toSMTVCs_cons :
    toSMTVCs ((E, ob) :: coreVCs) options = some vcs →
    ∃ label ctx ts t smtVCs, vcs = (label, ctx, ts, t) :: smtVCs ∧
    Core.ProofObligation.toSMTObligation E ob options = some (label, ctx, ts, t) ∧
    toSMTVCs coreVCs options = some smtVCs := by
  simp only [toSMTVCs, Option.bind_eq_bind, Option.bind]
  grind

namespace SMT

instance {α : Type u} {β : Type v} [hu : ToLevel.{u}] [hv : ToLevel.{v}] [ToExpr α] [ToExpr β] : ToExpr (Map α β) where
  toExpr m   := mkApp3 (.const ``Map.ofList [toLevel.{u}, toLevel.{v}]) (toTypeExpr α) (toTypeExpr β)
                       (@toExpr _ (@instToExprListOfToLevel _ ToLevel.max.{u, v} _) m.toList)
  toTypeExpr := mkApp2 (.const ``Map [toLevel.{u}, toLevel.{v}]) (toTypeExpr α) (toTypeExpr β)

deriving instance ToExpr for TermPrimType
deriving instance ToExpr for TermType
deriving instance ToExpr for TermVar
deriving instance ToExpr for UF
deriving instance ToExpr for TermPrim
deriving instance ToExpr for Op.Core
deriving instance ToExpr for Op.Num
deriving instance ToExpr for Op.BV
deriving instance ToExpr for Op.Strings
deriving instance ToExpr for Op.DatatypeFuncs
deriving instance ToExpr for Op.Arrays
deriving instance ToExpr for Op
deriving instance ToExpr for QuantifierKind
deriving instance ToExpr for SMT.Term
deriving instance ToExpr for Strata.DL.SMT.Sort
deriving instance ToExpr for IF
deriving instance ToExpr for SanitizedContext
deriving instance ToExpr for Core.CoreExprMetadata
deriving instance ToExpr for Lambda.LMonoTy

instance [ToExpr α] : ToExpr (Lambda.Identifier α) where
  toExpr id :=
    mkApp3 (.const ``Lambda.Identifier.mk []) (toTypeExpr α)
      (toExpr id.name)
      (toExpr id.metadata)
  toTypeExpr := mkApp2 (.const ``Lambda.Identifier []) (toTypeExpr String) (toTypeExpr α)

instance [ToExpr α] : ToExpr (Lambda.LConstr α) where
  toExpr c :=
    mkApp4 (.const ``Lambda.LConstr.mk []) (toTypeExpr α)
      (toExpr c.name)
      (toExpr c.args)
      (toExpr c.testerName)
  toTypeExpr := .app (.const ``Lambda.LConstr []) (toTypeExpr α)

instance [ToExpr α] : ToExpr (Lambda.LDatatype α) where
  toExpr dt :=
    mkApp5 (.const ``Lambda.LDatatype.mk []) (toTypeExpr α)
      (toExpr dt.name)
      (toExpr dt.typeArgs)
      (toExpr dt.constrs)
      (mkApp2 (.const ``Eq.refl [1]) (toTypeExpr Bool) (toExpr true))
  toTypeExpr := .app (.const ``Lambda.LDatatype []) (toTypeExpr α)

def _root_.Lambda.TypeFactory.ofList (dts : List (Lambda.MutualDatatype IDMeta))
  : @Lambda.TypeFactory IDMeta :=
  dts.foldl (fun tf dt => (tf.addMutualBlock dt).toOption.get!) Lambda.TypeFactory.default

instance [ToExpr α] : ToExpr (@Lambda.TypeFactory α) where
  toExpr tf := mkApp2 (.const ``Lambda.TypeFactory.ofList []) (toTypeExpr α) (toExpr tf.toList)
  toTypeExpr := .app (.const ``Lambda.TypeFactory []) (toTypeExpr α)

instance : ToExpr (Std.HashSet String) where
  toExpr s := mkApp4 (.const ``Std.HashSet.ofList [0]) (toTypeExpr String)
                     (mkApp2 (.const ``instBEqOfDecidableEq [0]) (toTypeExpr String) (.const ``instDecidableEqString []))
                     (.const ``instHashableString []) (toExpr s.toList)
  toTypeExpr := .app (.const ``Std.HashSet []) (toTypeExpr String)

def createGoal : SMTVC → MetaM MVarId := fun (label, ctx, ts, t) => do
  match translateQuery ctx.toCore ts t with
  | .error e =>
    logInfo m!"Error translating query"
    throwError e
  | .ok e =>
    trace[debug] "e := {e}"
    Meta.check e
    let .mvar mv ← Meta.mkFreshExprMVar e (userName := Translate.symbolToName label)
      | throwError "Failed to create goal"
    return mv

/-- The Lean name a generated datatype declaration would carry.

`DatatypeInductive` writes its declarations under `Strata.Gen`, quoting each
Core name so it survives verbatim. Guillemets are quoting syntax rather than
part of the name, so the components are used directly here. -/
def genName (components : List String) : Name :=
  components.foldl Name.str `Strata.Gen

/-- Resolve a generated declaration, allowing for the namespace it was
elaborated in. `DatatypeInductive.genPrefix` is relative, so a block emitted
inside `namespace Strata` lands under `Strata.Strata.Gen`. -/
def resolveGen (components : List String) : MetaM (Option Name) := do
  let env ← getEnv
  let base := genName components
  for cand in [base, `Strata ++ base] do
    if env.contains cand then return some cand
  return none

/-- The generated declaration a datatype function corresponds to.

Recovered from the symbol's own shape, the same way `DatatypeEncoding` built it:
`$dt.tag.D` is `D`'s tag, `D..f` is a selector, and anything else returning `D`
is one of its constructors. -/
def genComponentsOf (uf : UF) : Option (List String) :=
  if uf.id.startsWith "$dt.tag." then
    some [(uf.id.drop "$dt.tag.".length).toString, "tag"]
  else match uf.id.splitOn ".." with
    | [d, f] => some [d, f]
    | _ => match uf.out with
      | .constr d [] => some [d, uf.id]
      | _ => none

/-- Interpret a context's datatype symbols as the generated Lean declarations.

Anything with no generated counterpart is left out, and `translateQueryIn` then
quantifies over it as before. -/
def genDatatypeInterp (ctx : Core.SMT.Context) :
    MetaM (Std.HashMap Translate.Var (Lean.Expr × Lean.Expr)) := do
  let mut m : Std.HashMap Translate.Var (Lean.Expr × Lean.Expr) := {}
  for s in ctx.sorts.toList do
    if let some c ← resolveGen [s.name] then
      let ty := Lean.mkConst c
      let ne := Lean.mkApp (Lean.mkConst ``Nonempty [levelOne]) ty
      m := m.insert (.us s) (Lean.mkSort levelOne, ty)
      m := m.insert (.is s) (ne, ← Lean.Meta.synthInstance ne)
  for uf in ctx.ufs.toList do
    if let some cs := genComponentsOf uf then
      if let some c ← resolveGen cs then
        m := m.insert (.uf uf) ((← getConstInfo c).type, Lean.mkConst c)
  return m

/-- The carrier interpreting a sort, and the `Nonempty` witness for it.

`none` for a sort with no generated counterpart, which then stays quantified. -/
def sortCarrier (s : Strata.DL.SMT.Sort) : MetaM (Option String) := do
  if s.name == SMT.RealAbstraction.realSortName then
    return some "_root_.Strata.SMT.DatatypeInductive.Real"
  let some c ← resolveGen [s.name] | return none
  -- A generated block carrying a base type with no Lean image is parameterised
  -- over it; `real` is the only such type the Laurel prelude produces, so every
  -- parameter is applied to the same opaque carrier. The arity is read off the
  -- constant rather than recomputed, so this cannot drift from the generator.
  let mut ty ← Meta.inferType (Lean.mkConst c)
  let mut args := ""
  while ty.isForall do
    args := args ++ " _root_.Strata.SMT.DatatypeInductive.Real"
    ty := ty.bindingBody!
  -- `_root_`-anchored: the emitted text may be elaborated inside a namespace,
  -- and a relative name would resolve again against it.
  return some (if args.isEmpty then s!"_root_.{c}" else s!"(_root_.{c}{args})")

/-- Whether a function has a generated counterpart we can supply. -/
def ufResolvable (uf : UF) : MetaM Bool := do
  let some cs := genComponentsOf uf | return false
  return (← resolveGen cs).isSome

/-- How much of a context's head we can interpret, and how much of its tail. -/
def interpSplit (ctx : Core.SMT.Context) : MetaM (Nat × Nat) := do
  let uss := ctx.sorts.toList.reverse
  let ufs := ctx.ufs.toList.reverse
  let mut nSorts := 0
  for s in uss do
    if (← sortCarrier s).isSome then nSorts := nSorts + 1 else break
  let mut nUFs := 0
  for uf in ufs.reverse do
    if ← ufResolvable uf then nUFs := nUFs + 1 else break
  return (nSorts, nUFs)

/-- A `SuppliedInterp` for a program's datatypes, as Lean source.

Emitted as text and elaborated, matching how the inductives themselves are
produced: the declaration is dependently typed and every proof obligation in it
discharges by `rfl`, which the elaborator is far better placed to check than a
hand-built `Expr` would be. Literals go through `reprStr`, which round-trips as
fully-qualified Lean source, so the emitted `UF`s cannot drift from the ones the
encoder built. -/
def interpText (name : String) (ctx : Core.SMT.Context) : MetaM String := do
  -- `reprStr` wraps long values across lines. The generated declaration uses
  -- `where`-block layout, where a continuation at column 1 reads as the end of
  -- the field, so every rendered literal is flattened onto one line.
  let flat := fun {α : Type} [Repr α] (x : α) => (reprStr x).replace "\n" " "
  let uss := ctx.sorts.toList.reverse
  let ufs := ctx.ufs.toList.reverse
  let (nSorts, nUFs) ← interpSplit ctx
  let supUss := uss.take nSorts
  let supUfs := ufs.drop (ufs.length - nUFs)
  let mut sGamma := #[]
  for s in supUss do
    let some carrier ← sortCarrier s | throwError "no carrier for sort {s.name}"
    sGamma := sGamma.push
      s!"    \{ us := {flat s}, usΓ := {carrier}, nonempty := ⟨default⟩ }"
  let mut ufGamma := #[]
  for uf in supUfs do
    let some cs := genComponentsOf uf | throwError "no generated name for {uf.id}"
    let some c ← resolveGen cs | throwError "unresolved generated name for {uf.id}"
    ufGamma := ufGamma.push
      s!"    \{ uf := {flat uf}, h := rfl, ufΓ := _root_.{c} }"
  let list := fun (xs : Array String) =>
    if xs.isEmpty then "[]" else "[\n" ++ ",\n".intercalate xs.toList ++ "]"
  return s!"noncomputable def {name} : _root_.SuppliedInterp where\n" ++
    s!"  uss := {flat supUss}\n" ++
    s!"  sΓ := {list sGamma}\n" ++
    "  hsΓ := _root_.USEnvironment.wfOfMapEq rfl\n" ++
    s!"  ufs := {flat supUfs}\n" ++
    s!"  ufΓ := fun _ _ => {list ufGamma}\n" ++
    "  hufΓ := fun _ _ => _root_.UFEnvironment.wfOfMapEq rfl\n"

/-- `createGoal`, but with the datatype symbols interpreted rather than bound. -/
def createGoalIn : SMTVC → MetaM MVarId := fun (label, ctx, ts, t) => do
  let core := ctx.toCore
  let interp ← genDatatypeInterp core
  match _root_.translateQueryIn core interp ts t with
  | .error e =>
    logInfo m!"Error translating query under the generated interpretation"
    throwError e
  | .ok e =>
    Meta.check e
    let .mvar mv ← Meta.mkFreshExprMVar e (userName := Translate.symbolToName label)
      | throwError "Failed to create goal"
    return mv

end SMT

end Strata

end -- public section

namespace Strata

public section

namespace Meta

def andN (ps : List Lean.Expr) : Lean.Expr :=
  match ps with
  | [] => .const ``True []
  | p :: ps => go ps p
where
  go ps P : Lean.Expr :=
  match ps with
  | [] => P
  | p :: ps => go ps (mkApp2 (.const ``And []) P p)

def andNIntro (hps : List (Lean.Expr × Lean.Expr)) : Lean.Expr :=
  match hps with
  | [] => .const ``True.intro []
  | (p, hp) :: ps => go ps p hp
where
  go ps P hP : Lean.Expr :=
  match ps with
  | [] => hP
  | (p, hp) :: ps => go ps (mkApp2 (.const ``And []) P p) (mkApp4 (.const ``And.intro []) P p hP hp)

def nativeDecide (p : Lean.Expr) : MetaM Lean.Expr := do
  let hp ← Meta.synthInstance (.app (.const ``Decidable []) p)
  let auxDeclName ← mkNativeAuxDecl `_genSMTVCs (.const ``Bool []) (mkApp2 (.const ``decide []) p hp)
  let b := .const auxDeclName []
  return mkApp3 (.const ``of_decide_eq_true []) p hp
                (mkApp3 (.const ``Lean.ofReduceBool []) b (.const ``true [])
                        (mkApp2 (.const ``Eq.refl [1]) (.const ``Bool []) (.const ``true [])))
where
  mkNativeAuxDecl (baseName : Name) (type value : Lean.Expr) : MetaM Name := do
    let auxName ← Lean.mkAuxDeclName baseName
    let decl := Declaration.defnDecl {
      name := auxName, levelParams := [], type, value
      hints := .abbrev
      safety := .safe
    }
    addAndCompile decl
    pure auxName

private unsafe def genSMTVCsUnsafe (mv : MVarId) : MetaM (List MVarId) := do
  let type ← mv.getType
  let some (program, options) := type.app2? ``Strata.smtVCsCorrect
    | throwError "Expected a Strata.smtVCsCorrect goal"
  trace[debug] m!"Generating SMT VCs for {program}"
  let mv ← Meta.unfoldTarget mv ``Strata.smtVCsCorrect
  let ovcs := mkApp2 (.const ``Strata.genSMTVCs []) program options
  let ovcsType := .app (.const ``Option [0]) (.const ``Strata.SMT.SMTVCs [])
  let some evcs ← Meta.evalExpr (Option Strata.SMT.SMTVCs) ovcsType ovcs
    | throwError "Failed to generate VCs"
  trace[debug] m!"Generated {repr evcs}"
  let rhs := toExpr (some evcs)
  let eqVCs := mkApp3 (.const ``Eq [1]) ovcsType ovcs rhs
  let hEQVCs ← nativeDecide eqVCs
  let r ← mv.rewrite (← mv.getType) hEQVCs
  let mv ← mv.replaceTargetEq r.eNew r.eqProof
  let mvs ← evcs.mapM SMT.createGoal
  trace[debug] m!"Created {mvs.length} SMT VC goals: {mvs}"
  let ps ← mvs.mapM MVarId.getType
  let hP := andNIntro (List.zip ps (mvs.map Expr.mvar))
  let mvType ← mv.getType
  let bridgeType := Lean.Expr.forallE `h (andN ps) mvType .default
  let bridgeName ← Lean.mkAuxDeclName `_genSMTVCs_tcbBridge
  Lean.addDecl (Declaration.axiomDecl {
    name := bridgeName, levelParams := [], type := bridgeType, isUnsafe := false
  })
  mv.assign (mkApp (.const bridgeName []) hP)
  return mvs

@[implemented_by genSMTVCsUnsafe]
meta opaque genSMTVCs (mv : MVarId) : MetaM (List MVarId)

private unsafe def genSMTVCsInUnsafe (mv : MVarId) : MetaM (List MVarId) := do
  let type ← mv.getType
  let .const ``Strata.smtVCsCorrectIn _ := type.getAppFn
    | throwError "Expected a Strata.smtVCsCorrectIn goal"
  let #[program, _I, options] := type.getAppArgs
    | throwError "Expected a Strata.smtVCsCorrectIn goal"
  let mv ← Meta.unfoldTarget mv ``Strata.smtVCsCorrectIn
  let ovcs := mkApp2 (.const ``Strata.genSMTVCs []) program options
  let ovcsType := .app (.const ``Option [0]) (.const ``Strata.SMT.SMTVCs [])
  let some evcs ← Meta.evalExpr (Option Strata.SMT.SMTVCs) ovcsType ovcs
    | throwError "Failed to generate VCs"
  let rhs := toExpr (some evcs)
  let eqVCs := mkApp3 (.const ``Eq [1]) ovcsType ovcs rhs
  let hEQVCs ← nativeDecide eqVCs
  let r ← mv.rewrite (← mv.getType) hEQVCs
  let mv ← mv.replaceTargetEq r.eNew r.eqProof
  let mvs ← evcs.mapM SMT.createGoalIn
  let ps ← mvs.mapM MVarId.getType
  let hP := andNIntro (List.zip ps (mvs.map Expr.mvar))
  let mvType ← mv.getType
  let bridgeType := Lean.Expr.forallE `h (andN ps) mvType .default
  let bridgeName ← Lean.mkAuxDeclName `_genSMTVCsIn_tcbBridge
  Lean.addDecl (Declaration.axiomDecl {
    name := bridgeName, levelParams := [], type := bridgeType, isUnsafe := false
  })
  mv.assign (mkApp (.const bridgeName []) hP)
  return mvs

@[implemented_by genSMTVCsInUnsafe]
meta opaque genSMTVCsIn (mv : MVarId) : MetaM (List MVarId)

end Meta

end -- public section

public section

namespace Tactic

/--
Generate one Lean goal per SMT verification condition in a goal of the form
`Strata.smtVCsCorrect program`.
-/
syntax (name := genSMTVCs) "gen_smt_vcs" : tactic

open Lean Elab Tactic in
@[tactic genSMTVCs] meta def evalGenSMTVCs : Tactic := fun stx => do
  match stx with
  | `(tactic| gen_smt_vcs) =>
    let mvs ← Meta.genSMTVCs (← Tactic.getMainGoal)
    Tactic.replaceMainGoal mvs
  | _ => throwUnsupportedSyntax

/--
Generate one Lean goal per SMT verification condition in a goal of the form
`Strata.smtVCsCorrectIn program I`, with the datatype symbols interpreted as
their generated Lean declarations rather than universally quantified.
-/
syntax (name := genSMTVCsIn) "gen_smt_vcs_in" : tactic

open Lean Elab Tactic in
@[tactic genSMTVCsIn] meta def evalGenSMTVCsIn : Tactic := fun stx => do
  match stx with
  | `(tactic| gen_smt_vcs_in) =>
    let mvs ← Meta.genSMTVCsIn (← Tactic.getMainGoal)
    Tactic.replaceMainGoal mvs
  | _ => throwUnsupportedSyntax

end Tactic

end -- public section

end Strata
