/-
  Copyright Strata Contributors

  SPDX-License-Identifier: Apache-2.0 OR MIT
-/

import Strata.Languages.Core
import StrataDDM.Integration.Lean.HashCommands
import Strata.MetaVerifier
import StrataTest.DL.SMT.DatatypeInductiveTests

/-! # Verifying against a supplied interpretation

`smtVCsCorrect` quantifies over every interpretation of a program's datatypes,
so a datatype sort denotes to an arbitrary type and its tag to an arbitrary
function. Nothing then decides a tag test on a symbolic value -- which is the
shape every Laurel coercion takes, and so the blocking gap for verifying
translated Python. `StrataTest.DL.SMT.DatatypeEncodingTests` records that gap as
a `fail_if_success`.

`smtVCsCorrectIn` asks the same question of *one* interpretation instead, and
`gen_smt_vcs_in` supplies the generated inductive as that interpretation. The
two tests below are the pair that matters:

- exhaustiveness over a symbolic `v` now proves, where under `smtVCsCorrect` it
  cannot;
- `1 == 2` still does not, so nothing was bought with an inconsistency.

The second is the control that the earlier axiomatic encoding failed, and it is
the more important of the two.
-/

open StrataDDM (Program)
namespace Strata

-- `Strata.Gen.Val` is generated by `DatatypeInductiveTests` from a program with
-- this same datatype, so it is already in scope.
private def classifyPgm : Program :=
#strata
program Core;
datatype Val { VInt(getInt : int), VBool(getBool : bool), VNone() };
procedure classify (v : Val, out n : int)
spec {
  ensures [exhaustive]: Val..isVInt(v) || Val..isVBool(v) || Val..isVNone(v);
  ensures [absurd]: 1 == 2;
}
{
  $return: { n := 0; exit $return; }
};
#end

open Strata.SMT

private def valSort : Strata.DL.SMT.Sort := { name := "Val", arity := 0 }
private def valTy : TermType := .constr "Val" []

private def valSΓ : SortEnvironment :=
  [{ us := valSort, usΓ := Strata.Gen.«Val», nonempty := ⟨.«VNone»⟩ }]

-- The functions in binder order: the reverse of how the encoder emits them.
private def ufGetBool : UF := { id := "Val..getBool", args := [valTy], out := .prim .bool }
private def ufGetInt  : UF := { id := "Val..getInt",  args := [valTy], out := .prim .int }
private def ufVNone   : UF := { id := "VNone", args := [],            out := valTy }
private def ufVBool   : UF := { id := "VBool", args := [.prim .bool], out := valTy }
private def ufVInt    : UF := { id := "VInt",  args := [.prim .int],  out := valTy }
private def ufTag     : UF := { id := "$dt.tag.Val", args := [valTy], out := .prim .int }

/-- The whole point: every obligation below is discharged by `rfl`, because
supplying the sorts at the head of the context makes the environment reduce and
the types present as the generated ones. -/
noncomputable def valInterp : SuppliedInterp where
  uss := [valSort]
  sΓ := valSΓ
  hsΓ := USEnvironment.wfOfMapEq rfl
  ufs := [ufGetBool, ufGetInt, ufVNone, ufVBool, ufVInt, ufTag]
  ufΓ := fun _ _ =>
    [{ uf := ufGetBool, h := rfl, ufΓ := Strata.Gen.«Val».«getBool» },
     { uf := ufGetInt,  h := rfl, ufΓ := Strata.Gen.«Val».«getInt» },
     { uf := ufVNone,   h := rfl, ufΓ := Strata.Gen.«Val».«VNone» },
     { uf := ufVBool,   h := rfl, ufΓ := Strata.Gen.«Val».«VBool» },
     { uf := ufVInt,    h := rfl, ufΓ := Strata.Gen.«Val».«VInt» },
     { uf := ufTag,     h := rfl, ufΓ := Strata.Gen.«Val».tag }]
  hufΓ := fun _ _ => UFEnvironment.wfOfMapEq rfl

-- Dispatch on a symbolic scrutinee, restored. `cases` is available because the
-- sort denotes to a real inductive, and each tag test then reduces.
set_option maxRecDepth 1000000 in
set_option maxHeartbeats 1000000 in
theorem classify_exhaustive :
    smtVCsCorrectIn classifyPgm valInterp { onlyLabels := some ["exhaustive"] } := by
  gen_smt_vcs_in
  all_goals (intro v; cases v <;> simp [Strata.Gen.«Val».tag])

-- Consistency. The interpretation exhibits a datatype rather than describing
-- one, so there is nothing to be inconsistent, and a plainly false
-- postcondition must stay unprovable.
set_option maxRecDepth 1000000 in
set_option maxHeartbeats 1000000 in
example : True := by
  fail_if_success
    (have : smtVCsCorrectIn classifyPgm valInterp { onlyLabels := some ["absurd"] } := by
      gen_smt_vcs_in
      all_goals (intros; grind (splits := 100) (instances := 100000) (ematch := 100)))
  trivial

end Strata
